AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CertificateBucketName:
    Type: String # TODO: auslesen statt eingeben 
  ResultBucketName:
    Type: String # TODO: auslesen statt eingeben 
  LambdaS3Bucket:
    Type: String
  LambdaS3Object:
    Type: String

Resources:

  AnalyzeCertificatesFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Delete
    Properties:
      Handler: aws_lambda
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Object
      Runtime: go1.x
      Environment:
        Variables:
          cert-bucket: !Ref CertificateBucketName
          result-bucket: !Ref ResultBucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
