AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  NebulaLambdaBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: NebulaLambdaBucket
  CertificateBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: CertificateBucketName
  CertProcessResultBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: CertProcessResultBucketName
  LambdaS3Object:
    Type: String
    Default: aws_lambda.zip

Resources:
  AnalyzeCertificatesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: HandleLambdaRequest
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10
      Code:
        S3Bucket: !Ref NebulaLambdaBucket
        S3Key: !Ref LambdaS3Object
      Runtime: go1.x
      Environment:
        Variables:
          cert_bucket: !Ref CertificateBucketName
          result_bucket: !Ref CertProcessResultBucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
