AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaS3Bucket:
    Type: String
    Default: test-lambda-bucket-000991
  CertificateBucketName:
    Type: String
    Default: test-cert-bucket-000991
  ResultBucketName:
    Type: String
    Default: test-result-bucket-000991

Resources:

  #Store s3 buckets in SSM Parameter Store    
  LambdaBucketNameParamater:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Nebula cert check lambda S3 bucket
      Name: NebulaLambdaBucket
      Type: String
      Value: !Ref LambdaS3Bucket

  CertBucketNameParamater:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Nebula cert check S3 bucket
      Name: CertificateBucketName
      Type: String
      Value: !Ref CertificateBucketName

  CertProcessResultBucketNameParamater:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Nebula cert check S3 bucket
      Name: CertProcessResultBucketName
      Type: String
      Value: !Ref ResultBucketName

  #S3 Buckets
  LambdaBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref LambdaS3Bucket

  CertificateBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref CertificateBucketName 

  ResultBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref ResultBucketName