AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaS3Bucket:
    Type: String
    Required: true
  LambdaS3Object:
    Type: String
    Required: true
  CertificateBucketName:
    Type: String
    Required: true
  ResultBucketName:
    Type: String
    Required: true

Resources:

  AnalyzeCertificatesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: HandleLambdaRequest
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Object
      Runtime: go1.x
      Environment:
        Variables:
          cert-bucket: !Ref CertificateBucketName
          result-bucket: !Ref ResultBucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
    // TODO: S3 for 3 buckets for the lambda arn + me :) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
